version: '3.8'

services:
  db:
    image: postgres:15
    container_name: stemhub-db
    environment:
      POSTGRES_USER: stemuser
      POSTGRES_PASSWORD: stempass
      POSTGRES_DB: stemhub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
